version: "1.0"
services:
  app:
    build:
      args:
        user: realjay
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: tenancy
    depends_on:
      - db
    container_name: tenancy-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - tenancy

  db:
    image: mysql:8.0
    container_name: tenancy-db
    restart: unless-stopped
    ports:
      - 3309:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - tenancy
  
  nginx:
    image: nginx:1.17-alpine
    container_name: tenancy-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - tenancy


networks:
  tenancy:
    driver: bridge